name: 'Stage 5 Wordpress'
on: [workflow_dispatch]


jobs:
  container:
    name: 'Container Build'
    runs-on: ubuntu-latest
    environment: production
    
    env:
      registryName: "hackerkisteregistry"
      registryLoginServer: "hackerkisteregistry.azurecr.io"

    defaults:
      run:
        shell: bash
        #working-directory: ./container
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Environment
        run: |
          az aks get-credentials --resource-group ${{ secrets.UNIQUE_NAME }} --name ${{ secrets.UNIQUE_NAME }}

      - name: Docker Login to Registry
        run: |
          az acr login --name ${{ env.registryName }}

      - name: Deploy Manifests
        run: |
          kubectl apply -f ./stage_5_wordpress/
